export const GET_ERRORS ='GET_ERRORS';
export const GET_CONTACT ='GET_CONTACT';
export const CONTACT_LOADING ='CONTACT_LOADING';
export const DELETE_CONTACT ='DELETE_CONTACT';
export const GET_NEW_CONTACTS='GET_NEW_CONTACTS';
export const ADD_CONTACT='ADD_CONTACT';






 